-- ========================================================================
-- SCRIPT DE ACTUALIZACIÓN DE PRECIOS DE COSTO, PROVEEDORES Y RUC EN PRODUCTOS
-- ========================================================================

UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = 'OPI Distribuidor', proveedor_ruc = '1792938475001' WHERE nombre = 'Esmaltes Gel Pro';
UPDATE productos SET precio_costo = 2.09, fecha_compra = NULL, proveedor = 'Belleza Total S.A.', proveedor_ruc = '1792223334001' WHERE nombre = 'Removedor de acrílico premium';
UPDATE productos SET precio_costo = 1.74, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Aceite de cutícula coco 15ml';
UPDATE productos SET precio_costo = 0.22, fecha_compra = '2026-01-28', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'mascarillas facial';
UPDATE productos SET precio_costo = 10.87, fecha_compra = '2026-04-28', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'lamparas';
UPDATE productos SET precio_costo = 29.74, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'drill';
UPDATE productos SET precio_costo = 1.80, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'mascara ploma';
UPDATE productos SET precio_costo = 6.52, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'palos con algodón';
UPDATE productos SET precio_costo = 1.04, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'cepillos de pies';
UPDATE productos SET precio_costo = 0.70, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'limas  100/180';
UPDATE productos SET precio_costo = 0.70, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'limas 100/240';
UPDATE productos SET precio_costo = 0.70, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'lima 100/240 ESPONGI';
UPDATE productos SET precio_costo = 6.52, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'palos de colores rosados con algodón';
UPDATE productos SET precio_costo = 1.04, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'cepillos de cejas rosados';
UPDATE productos SET precio_costo = 5.72, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'caja de paletas';
UPDATE productos SET precio_costo = 1.52, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'wipe magic 5 x 5 cm';
UPDATE productos SET precio_costo = 3.91, fecha_compra = '2026-03-15', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'papel fim,rosados pestañas y cejas';
UPDATE productos SET precio_costo = 6.52, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Glam beauty';
UPDATE productos SET precio_costo = 2.20, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'parches funda ploma';
UPDATE productos SET precio_costo = 4.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'discos reemplazable sandig';
UPDATE productos SET precio_costo = 3.13, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Glue bolm 15 gr inconsign';
UPDATE productos SET precio_costo = 3.91, fecha_compra = '2026-03-15', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'rizadores de pestañas';
UPDATE productos SET precio_costo = 0.22, fecha_compra = '2026-06-15', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'frasco crema de manos';
UPDATE productos SET precio_costo = 7.50, fecha_compra = '2026-03-25', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'frasco de alcohol';
UPDATE productos SET precio_costo = 2.09, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'caja de acrilico wite';
UPDATE productos SET precio_costo = 2.09, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'caja de acrilico  clear';
UPDATE productos SET precio_costo = 2.09, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'caja de acrilico cover pink';
UPDATE productos SET precio_costo = 6.83, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Master Nail moldeador acrigel';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Master Nail smart gel royal clear';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Master Nail smar gel cover nude';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Master Nail smet gel Pink';
UPDATE productos SET precio_costo = 6.83, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Master Nail smart royal white';
UPDATE productos SET precio_costo = 0.70, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'frasco de acetona pequeño';
UPDATE productos SET precio_costo = 3.83, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'frasco gotero  monomero';
UPDATE productos SET precio_costo = 2.61, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'frasco o gotero removedor de cuticula';
UPDATE productos SET precio_costo = 6.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'ablandador de callos';
UPDATE productos SET precio_costo = 1.43, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'frascos de disolvente de esmalte';
UPDATE productos SET precio_costo = 1.96, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Master top coat';
UPDATE productos SET precio_costo = 3.91, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Tarro master polvo acrilico clear 460';
UPDATE productos SET precio_costo = 3.91, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'tarro master polvo acrilico wite';
UPDATE productos SET precio_costo = 3.91, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'tarro master polvo acrilico cover pink';
UPDATE productos SET precio_costo = 2.61, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'brochas limpiador rosada';
UPDATE productos SET precio_costo = 13.48, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'brpchas kolinsky numero 2';
UPDATE productos SET precio_costo = 5.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'pinceles estuche rosado';
UPDATE productos SET precio_costo = 1.74, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'punteros';
UPDATE productos SET precio_costo = 6.52, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'cucharas de  palo';
UPDATE productos SET precio_costo = 2.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'perfiladores largos 3 paquetes';
UPDATE productos SET precio_costo = 1.80, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'perfiladores mediano 3 unidades';
UPDATE productos SET precio_costo = 2.39, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'tijeras';
UPDATE productos SET precio_costo = 2.61, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'pinceles con brocha y cepillo';
UPDATE productos SET precio_costo = 2.35, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'pincel dorado';
UPDATE productos SET precio_costo = 2.17, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'imanes';
UPDATE productos SET precio_costo = 0.52, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'anillos para esmalte';
UPDATE productos SET precio_costo = 0.91, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'depiladores metalicos';
UPDATE productos SET precio_costo = 0.07, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'repunjador metalico de pedicura';
UPDATE productos SET precio_costo = 3.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'paquete  de repunjador metalico';
UPDATE productos SET precio_costo = 3.52, fecha_compra = '2026-06-08', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coquetas base coat';
UPDATE productos SET precio_costo = 4.30, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coqueta extremebond';
UPDATE productos SET precio_costo = 3.52, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coqueta blooming';
UPDATE productos SET precio_costo = 4.30, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coqueta nail pro';
UPDATE productos SET precio_costo = 6.83, fecha_compra = '2026-04-16', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'ez flow nail sistema natural nail primer';
UPDATE productos SET precio_costo = 6.83, fecha_compra = '2026-04-16', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Mia secret xtrabon nail primer 1-2';
UPDATE productos SET precio_costo = 7.83, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Mia secret  Nail prep';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'glan nails gel polish traslucido';
UPDATE productos SET precio_costo = 24.33, fecha_compra = '2026-02-17', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'thuya cola duo pestañas';
UPDATE productos SET precio_costo = 1.96, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'miss summer top coat';
UPDATE productos SET precio_costo = 4.30, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coquetas glue nail decorations';
UPDATE productos SET precio_costo = 3.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'gotas astricare mollie';
UPDATE productos SET precio_costo = 3.13, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'nail glue the original';
UPDATE productos SET precio_costo = 3.13, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'solon pro hair bonding glue';
UPDATE productos SET precio_costo = 3.52, fecha_compra = '2026-06-08', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'addict pro rubber base coat';
UPDATE productos SET precio_costo = 2.61, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'magic removedor am beauty';
UPDATE productos SET precio_costo = 1.96, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'mate top coat';
UPDATE productos SET precio_costo = 1.74, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'miss summer aceite cuticula';
UPDATE productos SET precio_costo = 1.74, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'ten coco aceite de cuticula';
UPDATE productos SET precio_costo = 1.43, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'secado rapido de esmalte ·# 45';
UPDATE productos SET precio_costo = 1.43, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'base Rodher';
UPDATE productos SET precio_costo = 1.43, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'esmaltes Rodhert tradicional';
UPDATE productos SET precio_costo = 6.83, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'master nail Rubber';
UPDATE productos SET precio_costo = 4.17, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'master nail esmalte';
UPDATE productos SET precio_costo = 1.17, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'esmalte saphir';
UPDATE productos SET precio_costo = 3.83, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'frasco monomero';
UPDATE productos SET precio_costo = 1.74, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'fundas diseño de uñas';
UPDATE productos SET precio_costo = 2.80, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'fundas de sacheto pps';
UPDATE productos SET precio_costo = 1.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'beauty tool cuchillas';
UPDATE productos SET precio_costo = 4.70, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'glan beauty pinzas para las pestañas';
UPDATE productos SET precio_costo = 7.83, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Mia secret implemento para pedicura';
UPDATE productos SET precio_costo = 0.61, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'glan nail profesional tools';
UPDATE productos SET precio_costo = 1.80, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'perfiladores de beauty eyebrow razo';
UPDATE productos SET precio_costo = 7.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'demert nail enamel dryer tarro rojo';
UPDATE productos SET precio_costo = 3.13, fecha_compra = '2026-02-24', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'parafina real honey';
UPDATE productos SET precio_costo = 3.13, fecha_compra = '2026-02-24', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'parafina Aloe Vera';
UPDATE productos SET precio_costo = 33.48, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'galon de exfoliante manos';
UPDATE productos SET precio_costo = 33.48, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'galon de exfoliante pies';
UPDATE productos SET precio_costo = 7.50, fecha_compra = '2026-03-25', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'galon de alcohol';
UPDATE productos SET precio_costo = 19.13, fecha_compra = '2026-04-12', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'galon de quita esmalte';
UPDATE productos SET precio_costo = 6.80, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'sandalias paquete + 8 pares';
UPDATE productos SET precio_costo = 2.61, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'galon removedor de cuticula';
UPDATE productos SET precio_costo = 13.04, fecha_compra = '2026-05-26', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'frasco de acetona pura';
UPDATE productos SET precio_costo = 3.83, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'monomero';
UPDATE productos SET precio_costo = 2.60, fecha_compra = '2026-06-24', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'paquete desmaquillante';
UPDATE productos SET precio_costo = 1.52, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'wipe  algodón';
UPDATE productos SET precio_costo = 1.52, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'wipe normal';
UPDATE productos SET precio_costo = 0.07, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'fundas pedicura';
UPDATE productos SET precio_costo = 4.43, fecha_compra = '2025-11-30', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'separadores rosados';
UPDATE productos SET precio_costo = 4.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'cofias';
UPDATE productos SET precio_costo = 10.43, fecha_compra = '2026-06-26', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'agua de rosas';
UPDATE productos SET precio_costo = 1.74, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'aceite de naranja';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'bulder gel clear Master nail';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'bulder gel sky pink Master nail';
UPDATE productos SET precio_costo = 6.83, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'white Master nail';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'bulder gel soft nude Master nail';
UPDATE productos SET precio_costo = 0.61, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'glan nails pink';
UPDATE productos SET precio_costo = 3.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'xeijayi';
UPDATE productos SET precio_costo = 3.52, fecha_compra = '2026-02-11', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coqueta rubber base 4';
UPDATE productos SET precio_costo = 3.52, fecha_compra = '2026-02-11', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coqueta rubber base 10';
UPDATE productos SET precio_costo = 4.30, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coqueta rubber 6';
UPDATE productos SET precio_costo = 4.30, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coqueta rubber  18';
UPDATE productos SET precio_costo = 3.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'esmalte xeijayi';
UPDATE productos SET precio_costo = 2.17, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'ojo de gato linda';
UPDATE productos SET precio_costo = 2.17, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'coqueta superbright ojo de gato';
UPDATE productos SET precio_costo = 2.61, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'L &D OJO  de gato';
UPDATE productos SET precio_costo = 2.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'Addict ojo de gato';
UPDATE productos SET precio_costo = 2.17, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'linda escarcha';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'glan nail gel polish';
UPDATE productos SET precio_costo = 10.00, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'bolas efervecentes';
UPDATE productos SET precio_costo = 4.20, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'caja de peitn de temo';
UPDATE productos SET precio_costo = 0.87, fecha_compra = '2026-01-14', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'caja de esponjas para difuminar';
UPDATE productos SET precio_costo = 1.74, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'aceite para cuticula revitalizador';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'rimel gel rosemary';
UPDATE productos SET precio_costo = 4.35, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'rimel  prosa  mascara';
UPDATE productos SET precio_costo = 3.50, fecha_compra = '2026-06-01', proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'piedreria';
UPDATE productos SET precio_costo = 3.22, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'cajas de sof gel tips';
UPDATE productos SET precio_costo = 3.00, fecha_compra = NULL, proveedor = NULL, proveedor_ruc = NULL WHERE nombre = 'cajas de polygel';